# Generated by Django 4.1.7 on 2023-11-05 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название типа бизнеса"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание типа бизнеса"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Название бизнеса должно быть уникальным и не использоваться другими компаниями в вашей юрисдикции.",
                        max_length=200,
                        unique=True,
                        verbose_name="Название компании",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Необязательно.",
                        verbose_name="Описание деятельности",
                    ),
                ),
                (
                    "chairman_of_board",
                    models.CharField(
                        max_length=100, verbose_name="Председатель правления"
                    ),
                ),
                (
                    "chairman_of_management_board",
                    models.CharField(
                        max_length=100, verbose_name="Председатель совета директоров"
                    ),
                ),
                (
                    "board_of_directors",
                    models.TextField(
                        help_text="ФИО через запятую", verbose_name="Совет директоров"
                    ),
                ),
                (
                    "members_of_management_board",
                    models.TextField(
                        help_text="ФИО через запятую", verbose_name="Члены правления"
                    ),
                ),
                (
                    "chief_accountant",
                    models.CharField(max_length=100, verbose_name="Главный бухгалтер"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        help_text="Введите ИИН если вы индивидуальный предприниматель, БИН в другом случае.",
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите 12-й номер", regex="^\\d{12}$"
                            )
                        ],
                        verbose_name="Введите ИИН или БИН",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="Адрес компании"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="KZ",
                        verbose_name="Номер телефона компании",
                    ),
                ),
                (
                    "fax",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="KZ", verbose_name="Факс"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Электронный адрес компании"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Необязательно.",
                        verbose_name="Веб-сайт компании",
                    ),
                ),
                (
                    "custodian_license",
                    models.CharField(
                        blank=True,
                        help_text="Необязательно",
                        max_length=100,
                        null=True,
                        verbose_name="Кастодиан",
                    ),
                ),
                (
                    "broker_license",
                    models.CharField(
                        help_text="Необязательно",
                        max_length=100,
                        verbose_name="Брокеры-дилеры",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Необязательно",
                        upload_to="company_images/",
                        verbose_name="Логотип или фото компании",
                    ),
                ),
                (
                    "business_type",
                    models.ForeignKey(
                        help_text="Выберите тип бизнеса, которым занимается компания.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="enterprises.businesstype",
                        verbose_name="Тип бизнеса",
                    ),
                ),
                (
                    "curators",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="banks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кураторы",
                    ),
                ),
                (
                    "holdings",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="holdings",
                        to="enterprises.company",
                        verbose_name="Холдинги",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enterprises",
            },
        ),
        migrations.CreateModel(
            name="OwnershipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название формы собственности"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание формы собственности"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Financials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                        ],
                        help_text="За какой год информация ниже актуальна",
                        verbose_name="Отчет за год",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Показывает общую сумму денег, которую компания заработала за определенный год",
                        max_digits=10,
                        null=True,
                        verbose_name="Общая выручка",
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Поле может включать все расходы, связанные с бизнесом, такие как зарплата сотрудников, аренда помещения, закупка оборудования и т.д.",
                        max_digits=10,
                        null=True,
                        verbose_name="Расходы",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле показывает разницу между выручкой и себестоимостью товаров или услуг.",
                        max_digits=10,
                        null=True,
                        verbose_name="Валовая прибыль",
                    ),
                ),
                (
                    "net_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле может показывать сумму денег, которую компания заработала после вычета всех расходов.",
                        max_digits=10,
                        null=True,
                        verbose_name="Чистая прибыль",
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле может включать информацию о том, сколько налогов компания заплатила за определенный период времени.",
                        max_digits=10,
                        null=True,
                        verbose_name="Налоги",
                    ),
                ),
                (
                    "dividends",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле может показывать сумму денег, которую компания выплатила своим акционерам",
                        max_digits=10,
                        null=True,
                        verbose_name="Дивиденды",
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле показывает процентную прибыль компании, которая остается после вычета всех расходов от общей выручки.",
                        max_digits=10,
                        null=True,
                        verbose_name="Маржа",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprises.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Необязательно",
                        max_length=255,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронный адрес"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="KZ", verbose_name="Номер телефона"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Необязательно",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Необязательно",
                        upload_to="employee_images/",
                        verbose_name="Фото сотрудника",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        help_text="Необязательно",
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="enterprises.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="company",
            name="ownership_type",
            field=models.ForeignKey(
                help_text="Выберите форму собственности, которой принадлежит компания.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="enterprises.ownershiptype",
                verbose_name="Форма собственности",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
